# Generated by Django 4.0 on 2021-12-29 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numberform', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={},
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='pub_date',
        ),
    ]
